### ISSUE TITLE
Current live Page is Broken and Shows a Template Error

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-tutorial-razor#16]
This page appears to be broken...
https://2sxc.org/dnn-tutorials/en/razor/tut/quickref

The page output stops after, "Magic with Strings" (under Work with Content Items) for me. It looks like the accordion is broken (maybe unbalanced HTML tags?) and the remaining are all re-nested incorrectly. And as you can see that Result/Source output is throwing an error.
![image](https://github.com/user-attachments/assets/d1ed52bf-e974-4a97-a68b-21acc37eed5d)

**Comment by iJungleboy** [comment]
thanks!

is fixed in 18.01

**Comment by jeremy-farrance** [comment]
So these only get published on a release? The live site is still broken.

**Comment by iJungleboy** [comment]
Yes, hope to release this week.

**Comment by jeremy-farrance** [comment]
Is there a way to fix the _website_ so its useful again now?
